/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.4
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "PWM_1.h"
#include "PWM_2.h"
#include "PWM_3.h"
#include "PWM_4.h"
#include "Servo_1_aliases.h"
#include "Servo_1.h"
#include "Servo_2_aliases.h"
#include "Servo_2.h"
#include "Servo_3_aliases.h"
#include "Servo_3.h"
#include "Servo_4_aliases.h"
#include "Servo_4.h"
#include "Clock_1.h"
#include "SPI.h"
#include "SPI_PVT.h"
#include "Clock_2.h"
#include "MISO_aliases.h"
#include "MISO.h"
#include "MOSI_aliases.h"
#include "MOSI.h"
#include "CLK_aliases.h"
#include "CLK.h"
#include "SS_aliases.h"
#include "SS.h"
#include "isr_1.h"
#include "UART_1.h"
#include "UART_1_IntClock.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

